### ISSUE TITLE
Using custom R code for a Table/Figure legend

### ISSUE THREAD

**Issue by mattfidler** [john-harrold/onbrand#11]
Hi John,

I was wondering if you can use custom R code for a Table/Figure legend.  

I some officer code that creates the table and figure numbers for internal reports using `slip_in_seqfield()` to support the required internal format for tables and figures.  

I couldn't find the function used in this onbrand package and would like to include it as an option for my reports.

**Comment by john-harrold** [comment]
This push, https://github.com/john-harrold/onbrand/commit/28e94a0aa271fffd77453f087f84b98a7028d813 , should address this. It adds a couple options to the yaml file.  First it allows you to define the sequence ID used for tables and figures. Second it allows you to specify R code to define the numbering. I've also updated the documentation to provide an example of how to create table and figure numbers based on the current section.  

Lastly, to ensure that table and figure numbers reset within headings, I added an option fig_start_at and tab_start_at to this function:

http://onbrand.ubiquity.tools/reference/report_add_doc_content.html

You'll need to set those values to 1 when adding level 1 headings.

**Comment by mattfidler** [comment]
Do you also have a post-processing hook?

(Of course I could do it myself, but I am just wondering if it can be contained in the yaml or something similar.

**Comment by john-harrold** [comment]
I'll reopen this to add the post-processing option as well.

**Comment by mattfidler** [comment]
Thanks John!

I will look at this soon (probably after ACoP)

**Comment by john-harrold** [comment]
Ok I added the ability to insert R code for post-processing into the yaml file. If you look through this vignette it _should_ explain it.

http://onbrand.ubiquity.tools/articles/Custom_Office_Templates.html

I'd probably use the fetch and set functions to debug what you're trying to do. Once you have that working, then I'd take that code and stick it into the yaml file.

http://onbrand.ubiquity.tools/reference/fetch_officer_object.html
http://onbrand.ubiquity.tools/reference/set_officer_object.html
